name: Hilaight AI Daily Post

permissions:
  contents: write
on:
  schedule:
    - cron: "0 4 * * *"  # Runs daily at 4 AM UTC
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.HILAIGHT_BOT }}
            
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests feedparser

      - name: Run generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python auto_generate.py

      - name: Commit & Push
        run: |
          git config user.name "hilaight-bot"
          git config user.email "bot@hilaight.com"
      
          git add _posts/
      
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "ðŸ¤– Hilaight AI daily post"
            git push origin main
          fi
